stages:
  - quality gate

quality:
  stage: quality gate
  image:
    name: microsoft/dotnet:2.2-sdk-bionic
    entrypoint: ["/bin/bash"]
  allow_failure: true
  script:
    - apk add --no-cache --update openjdk8-jre nss
  only:
    refs:
      - branches
  except:
    refs:
      - master
      - SWAGGERHUB
  artifacts:
    expire_in: 1 hour
