stages:
  - quality gate

quality:
  stage: quality gate
  image:
    name: microsoft/dotnet:2.2-sdk-bionic
    entrypoint: [
      "/bin/bash"
    ]
  allow_failure: true
  script:
    - wget https://raw.githubusercontent.com/vidalink/gitlab-ci-yaml/master/dotnet/sonar/setup-sonar.sh -O setup-sonar.sh
    - setup-sonar.sh
  only:
    refs:
      - branches
  except:
    refs:
      - master
      - SWAGGERHUB
  artifacts:
    expire_in: 1 hour
