# Template to be used by projects that push libraries to nuget repository
# PROJECT_PATH => node project path
# PROJECT_PATH_TEST => node project path test
# NODE_DOCKER_IMAGE => node docker image
# DOCKER_IMAGE_NAME => docker image name to registry
# NPM_SOURCE_URL => npm auth url
image: ${NODE_DOCKER_IMAGE}

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test
  - package

docker-build:
  image: docker:stable
  stage: build
  script:
    - docker build -t ${DOCKER_IMAGE_NAME} ${PROJECT_PATH}
  only:
    variables:
      - $DOCKER_IMAGE_NAME

push-package:
  stage: package
  script:    
    - npm install ${PROJECT_PATH} -g    
    - npm run build --prefix ${PROJECT_PATH}
    - npm config set registry ${NPM_SOURCE_URL}
    - npm publish --prefix ${PROJECT_PATH}
  only:
    refs:
      - master
    variables:
      - $NPM_SOURCE_URL

test:
  stage: test
  script:
    - npm install --prefix ${PROJECT_PATH_TEST}
    - npm test --prefix ${PROJECT_PATH_TEST}
  only:
    variables:
      - $PROJECT_PATH_TEST
