image: alpine:latest

variables:
  CI_DEBUG_TRACE: "false"
  CODE_QUALITY_DISABLED: "true"
  DEPENDENCY_SCANNING_DISABLED: "true"
  PERFORMANCE_DISABLED: "true"
  POSTGRES_ENABLED: "false"
  TEST_DISABLED: "true"
  COLLECTION: collection.json
  COLLECTION_VARS: collection_vars.json

stages:
  - build
  - test
  - deploy 
  - review
  - dast
  - staging
  - canary
  - validation
  - production
  - incremental rollout 10%
  - incremental rollout 25%
  - incremental rollout 50%
  - incremental rollout 100%
  - performance
  - cleanup

include:
  - template: Auto-DevOps.gitlab-ci.yml

env url output:
  script:
  - $CI_ENVIRONMENT_URL >> CI_ENVIRONMENT_URL.txt
  only:
    variables:
      - $CI_ENVIRONMENT_URL != ""

run postman collection:
  stage: validation
  image: 
    name: postman/newman
    entrypoint: ["/bin/sh", "-c"]
  allow_failure: true
  script:
  - export CI_ENVIRONMENT_URL=$(cat CI_ENVIRONMENT_URL.txt)
  - sed -i 's/$CI_ENVIRONMENT_URL/'"$CI_ENVIRONMENT_URL"'/g' $COLLECTION_VARS
  - cat $COLLECTION_VARS
  - newman --version
  - newman run $COLLECTION -e $COLLECTION_VARS
