image: alpine:latest

variables:
  CI_DEBUG_TRACE: "false"
  CODE_QUALITY_DISABLED: "true"
  DEPENDENCY_SCANNING_DISABLED: "true"
  PERFORMANCE_DISABLED: "true"
  POSTGRES_ENABLED: "false"
  TEST_DISABLED: "true"

stages:
  - build
  - test
  - deploy 
  - review
  - dast
  - staging
  - canary
  - validation
  - production
  - incremental rollout 10%
  - incremental rollout 25%
  - incremental rollout 50%
  - incremental rollout 100%
  - performance
  - cleanup

include:
  - template: Auto-DevOps.gitlab-ci.yml

run postman collection:
  stage: validation
  image: 
    name: postman/newman
    entrypoint: ["/bin/sh", "-c"]
  allow_failure: true
  script:
  - newman --version
  - newman run collection.json -e prod.postman_environment.json
