image: alpine:latest

variables:
  CI_DEBUG_TRACE: "false"
  CODE_QUALITY_DISABLED: "true"
  DEPENDENCY_SCANNING_DISABLED: "true"
  PERFORMANCE_DISABLED: "true"
  POSTGRES_ENABLED: "false"
  TEST_DISABLED: "true"
  COLLECTION: collection.json
  COLLECTION_VARS: collection_vars.json

stages:
  - build
  - test
  - deploy 
  - review
  - dast
  - staging
  - canary
  - validation
  - production
  - incremental rollout 10%
  - incremental rollout 25%
  - incremental rollout 50%
  - incremental rollout 100%
  - performance
  - cleanup

include:
  - template: Auto-DevOps.gitlab-ci.yml

postman:
  stage: validation
  image: 
    name: postman/newman
    entrypoint: ["/bin/sh", "-c"]
  allow_failure: true
  script:
    - export ENV_URL=http://$CI_PROJECT_ID-$CI_ENVIRONMENT_SLUG.$KUBE_INGRESS_BASE_DOMAIN
    - echo $ENV_URL
    - sed -i 's#$CI_ENVIRONMENT_URL#'"$ENV_URL"'#g' $COLLECTION_VARS
    - newman --version
    - newman run $COLLECTION -e $COLLECTION_VARS
  only:
    refs:
      - branches
  except:
    refs:
      - master
    variables:
      - $POSTMAN_ENABLED
