image: alpine:latest

variables:
  CI_DEBUG_TRACE: "false"
  CODE_QUALITY_DISABLED: "true"
  DEPENDENCY_SCANNING_DISABLED: "true"
  PERFORMANCE_DISABLED: "true"
  POSTGRES_ENABLED: "false"
  TEST_DISABLED: "true"

before_script:
  - if [ "$CI_COMMIT_REF_NAME" = "master" ]; then export KUBE_INGRESS_BASE_DOMAIN='svc.cluster.local'; fi

stages:
  - build
  - quality gate
  - test
  - deploy
  - review
  - dast
  - staging
  - canary
  - validation
  - production
  - incremental rollout 10%
  - incremental rollout 25%
  - incremental rollout 50%
  - incremental rollout 100%
  - performance
  - cleanup

include:
  - template: Auto-DevOps.gitlab-ci.yml

postman_scenarios:
  stage: validation
  image: 
    name: postman/newman
    entrypoint: ["/bin/sh", "-c"]
  allow_failure: true
  script:
    - export CI_ENVIRONMENT_URL=$(cat environment_url.txt)
    - sed -i 's#%%URL%%#'"$CI_ENVIRONMENT_URL"'#g' $COLLECTION_VARS
    - wget https://raw.githubusercontent.com/vidalink/gitlab-ci-yaml/master/convert_test_cases.js -O convert_test_cases.js
    - newman --version
    - for scen in ${COLLECTION_SCENARIOS}.*.json; do node convert_test_cases "$scen" converted_scenarios.json; newman run $COLLECTION -e $COLLECTION_VARS --folder $(echo $scen | awk -F'.' '{print $2}') -d converted_scenarios.json --delay-request 100; done;
  only:
    refs:
      - branches
    variables:
      - $COLLECTION && $COLLECTION_VARS && $COLLECTION_SCENARIOS
  except:
    refs:
      - master
      
postman:
  stage: validation
  image: 
    name: postman/newman
    entrypoint: ["/bin/sh", "-c"]
  allow_failure: true
  script:
    - export CI_ENVIRONMENT_URL=$(cat environment_url.txt)
    - sed -i 's#%%URL%%#'"$CI_ENVIRONMENT_URL"'#g' $COLLECTION_VARS
    - newman --version
    - newman run $COLLECTION -e $COLLECTION_VARS --delay-request 100
  only:
    refs:
      - branches
    variables:
      - $COLLECTION && $COLLECTION_VARS
  except:
    refs:
      - master
    variables:
      - $COLLECTION_SCENARIOS

quality:
  stage: quality gate
  image:
    name: ${DOTNET_DOCKER_IMAGE}
    entrypoint: ["/bin/sh", "-c"]
  allow_failure: true
  script:
    - apk add --no-cache --update openjdk8-jre nss
    - dotnet tool install --global dotnet-sonarscanner
    - export PATH=${PATH}:/root/.dotnet/tools
    - dotnet test ${PROJECT_TEST_PATH} /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    - dotnet sonarscanner begin /k:"${SONAR_K}"  /d:sonar.host.url="${SONAR_HOST_URL}" /d:sonar.language="cs" /d:sonar.exclusions="**/bin/**/*,**/obj/**/*" /d:sonar.login="${SONAR_LOGIN}"  /d:sonar.cs.opencover.reportsPaths="${PROJECT_TEST_PATH}/coverage.opencover.xml" /d:sonar.coverage.exclusions="**Test*.cs"
    - dotnet restore --configfile ${PROJECT_API_PATH}/nuget.config ${PROJECT_API_PATH}
    - dotnet restore --configfile ${PROJECT_TEST_PATH}/nuget.config ${PROJECT_TEST_PATH}
    - dotnet build ${PROJECT_SLN_PATH}
    - dotnet sonarscanner end /d:sonar.login=${SONAR_LOGIN}
  only:
    refs:
      - branches
    variables:
      - $SONAR_K && $DOTNET_DOCKER_IMAGE
  except:
    refs:
      - master
      - SWAGGERHUB
