# Template to be used by projects that push libraries to nuget repository
# PROJECT_PATH => node project path
# PROJECT_PATH_TEST => node project path test
# NODE_DOCKER_IMAGE => node docker image
# DOCKER_IMAGE_NAME => docker image name to registry
# NPM_SOURCE_URL => npm auth url
image: ${NODE_DOCKER_IMAGE}

services:
  - docker:dind

stages:
  - build
  - test
  - package

docker-build:
  stage: build
  script:
    - docker build -t ${CI_PROJECT_NAMESPACE} ${SOLUTION_PATH}
  only:
    variables:
      - $CI_PROJECT_NAMESPACE && $SOLUTION_PATH

push-package:
  stage: package
  script:
    - npm install --prefix ${SOLUTION_PATH} -g
    - npm publish ${SOLUTION_PATH} --registry=${NPM_SOURCE_URL}
  only:
    refs:
      - master
    variables:
      - $NPM_SOURCE_URL && SOLUTION_PATH

test:
  stage: test
  script:
    - npm install --prefix ${PROJECT_PATH_TEST}
    - npm test --prefix ${PROJECT_PATH_TEST}
  only:
    variables:
      - $PROJECT_PATH_TEST
