image: node:carbon

stages:
  - build
  - test
  - package

 services:
  - docker:dind

variables:
  DOCKER_HOST: 'tcp://docker:2375'
  DOCKER_DRIVER: 'overlay2'

docker-build:
  image: docker:stable
  stage: build
  script:
    - docker build -t $CI_PROJECT_NAMESPACE $SOLUTION_PATH
  only:
    variables:
      - $CI_PROJECT_NAMESPACE && $SOLUTION_PATH

push-package:
  stage: package
  script:
    - npm install --prefix $SOLUTION_PATH -g
    - npm publish $SOLUTION_PATH --registry=$NPM_SOURCE_URL
  only:
    refs:
      - master
    variables:
      - $NPM_SOURCE_URL && $SOLUTION_PATH

test:
  stage: test
  script:
    - npm install --prefix $PROJECT_PATH_TEST
    - npm test --prefix $PROJECT_PATH_TEST
  only:
    variables:
      - $PROJECT_PATH_TEST
