image: alpine:latest

before_script:
  - export CI_DEBUG_TRACE=true
  - export CODE_QUALITY_DISABLED=true
  - export DEPENDENCY_SCANNING_DISABLED=true
  - export PERFORMANCE_DISABLED=true
  - export POSTGRES_ENABLED=false
  - export TEST_DISABLED=true
  - if [ ! $DOTNET_SDK_DOCKER_IMAGE ]; then export DOTNET_SDK_DOCKER_IMAGE='microsoft/dotnet:2.2-sdk-alpine'; fi
  - printenv

stages:
  - build
  - quality gate
  - test
  - deploy
  - review
  - dast
  - staging
  - canary
  - validation
  - production
  - incremental rollout 10%
  - incremental rollout 25%
  - incremental rollout 50%
  - incremental rollout 100%
  - performance
  - cleanup

include:
  - template: Auto-DevOps.gitlab-ci.yml
  - remote: 'https://raw.githubusercontent.com/vidalink/gitlab-ci-yaml/master/templates/dotnet/sonar/.gitlab-ci-template.yml'
  - remote: 'https://raw.githubusercontent.com/vidalink/gitlab-ci-yaml/master/templates/postman/.gitlab-ci-template.yml'
