#obrigatório
#NUGET_KEY: 634138b1-d6aa-4db6-b388-b583b5c2f855
#NUGET_SOURCE_URL: https://www.myget.org/F/vidalink/auth/634138b1-d6aa-4db6-b388-b583b5c2f855/api/v3/index.json
#opcional
#DOTNET_SDK_DOCKER_IMAGE
services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

before_script:
  - printenv
  - if [ ! $DOTNET_SDK_DOCKER_IMAGE ]; then export DOTNET_SDK_DOCKER_IMAGE='microsoft/dotnet:2.2-sdk-alpine'; fi

stages:
  - quality gate
  - package

push:
  stage: package
  image: ${DOTNET_SDK_DOCKER_IMAGE}
  script:
    - dotnet build -c Release -p:maxcpucount=5
    - dotnet pack -c Release --no-build
    - dotnet nuget push ./**/*.nupkg ${NUGET_KEY} --source ${NUGET_SOURCE_URL}
  only:
    refs:
      - master
