image: alpine:latest

stages:
  - build
  - deploy

compile:
  stage: build
  environment: production
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  script:
    - docker build -t ${CI_PROJECT_PATH_SLUG} .
  only:
    refs:
      - teste
    variables:
      - $BUILD_DOCKER_IMAGE && $D

publish:
  stage: deploy
  image: google/cloud-sdk:latest
  environment: production
  script:
    - printenv
    - export TMP_FILE=/tmp/${CI_PIPELINE_ID}.json
    - export TAG=gcr.io/${CLOUDSDK_CORE_PROJECT}/${CI_PROJECT_PATH_SLUG}:${CI_PIPELINE_ID}
    - echo ${GCLOUD_SERVICE_ACCOUNT} > ${TMP_FILE}
    - gcloud auth activate-service-account --key-file ${TMP_FILE}
    - gcloud builds submit --tag ${TAG}
    - gcloud beta run deploy ${CI_PROJECT_PATH_SLUG} --image ${TAG} --platform managed --region ${GCLOUD_PROJECT_REGION}
  only:
    refs:
      - teste
    variables:
      - $GCLOUD_PROJECT_REGION

after_script:
- rm ${TMP_FILE}
